version: "3.9"

services:
  react-vite:
    container_name: cloking-www
    build:
      context: .
      dockerfile: .docker/Dockerfile
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./application:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
